require_relative '../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '14.0'

target 'Plugin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
  pod 'GoogleSignIn', '~> 7.1.0'
end

target 'PluginTests' do
  use_frameworks!

  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
end

post_install do |installer|
  assertDeploymentTarget(installer)
end