name: android Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      API_LEVEL: 34
      EMULATOR: pixel_3
      TARGET: google_apis
      ABI: arm64-v8a # x86_64 requires hardware acceleration
      CHANNEL: 3
      ANDROID_HOME: /opt/android
      ANDROID_AVD_HOME: /root/.android/avd

    container:
      image: reactnativecommunity/react-native-android:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Install Android SDK and Emulator
      run: |
        set -e
        echo "y" | sdkmanager --channel=$CHANNEL "emulator"
        echo "y" | sdkmanager --channel=$CHANNEL "platform-tools"
        echo "y" | sdkmanager --channel=$CHANNEL "system-images;android-$API_LEVEL;$TARGET;$ABI"

    - name: Create and List AVD
      run: |
        set -e
        echo "no" | avdmanager create avd -n test -k "system-images;android-$API_LEVEL;$TARGET;$ABI" --force
        echo ""
        avdmanager list avd
        ls -al $ANDROID_AVD_HOME

    - name: Prepare and Start Emulator
      run: |
        set -e
        $ANDROID_HOME/emulator/emulator -avd test -no-window -no-snapshot -no-boot-anim -no-audio -gpu swiftshader_indirect -accel on &
        echo "calling wait-for-emulator"
        timeout 5m adb wait-for-device
        adb shell settings put global window_animation_scale 0
        adb shell settings put global transition_animation_scale 0
        adb shell settings put global animator_duration_scale 0
        adb shell input keyevent 82

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Run Instrumented Tests
      run: ./gradlew connectedAndroidTest

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: app/build/reports/
