name: JavaScript Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Rollup binding for linux
      run: npm install @rollup/rollup-linux-x64-gnu --save-optional

    - name: Install Node.js dependencies
      run: npm install

    - name: Run tests
      run: npm run test:web
